# firmware/core/sources.cmake — the ONE list of firefly-core's C sources.
#
# Shared, verbatim, by two differently-shaped consumers:
#   - the sim build (firmware/core/CMakeLists.txt):
#       add_library(ff-core STATIC ${FF_CORE_SOURCES})
#   - the esp32s3 IDF component
#     (firmware/targets/esp32s3/components/ff_core/CMakeLists.txt):
#       idf_component_register(SRCS <FF_CORE_SOURCES, each prepended with
#       the absolute path to firmware/core/> ...)
#
# Before this file existed, both call sites hand-copied this list and
# matched only by discipline — house lesson #112 bans file(GLOB) for the
# actual build (a stray non-source .c dropped under src/ would silently
# get compiled in), so there was no mechanical way to keep the sim and
# the device target's source lists in sync. Now there is exactly ONE
# place to add a new core/src/*.c file. ff_check_sources_complete()
# (defined in the top-level firmware/CMakeLists.txt, invoked from
# firmware/core/CMakeLists.txt) fails `cmake` configure with a
# named-file error if core/src/ and this list ever drift apart — see
# that function's own comment. That check runs only for the sim build
# (the IDF component tree never includes firmware/CMakeLists.txt), but
# since both consumers read this same FF_CORE_SOURCES variable, a
# complete sim-side list is a complete device-side list too.
#
# Paths are relative to this directory (firmware/core/). ff_flare_mark.h
# (core/include/) is deliberately NOT here — it's header-only, no .c to
# add; see that header's own top comment.
set(FF_CORE_SOURCES
    src/ff_version.c
    src/ff_settings.c      # S11 — settings & persistence
    src/ff_touchcal.c      # S15d — touch calibration (per-axis affine solve/apply)
    src/ff_geo.c            # S01 — bearing, distance, heading fusion
    src/ff_proto.c          # S04 — firefly protocol (flare/rally/status packets)
    src/ff_crew.c           # S02 — crew model & freshness
    src/ff_radar.c          # S06 — radar-face view compute
    src/ff_t9.c              # S08a — multi-tap T9 text-entry engine
    src/ff_t9pred.c          # S08 predictive-T9 addendum — dictionary + ranking engine
    src/ff_t9dict_data.c     # generated by core/tools/gen_t9dict.py — see core/tools/NOTICE-t9dict.md
    src/ff_flare.c           # S10a — flare state machine
    src/ff_feed.c            # S08b — Signals-face event ring buffer
    src/ff_heard.c           # S08b follow-up — bounded LRU-evictable heard-node list
    src/ff_wall.c            # S16 slice b0 — wall-clock derivation
    src/ff_map.c             # S09 — map-face fixed-fit camera transform
    src/ff_sigview.c         # core/sigview — honest presence classifier + ff_target_kind_t
    src/ff_demofeed.c        # S23a — deterministic seeded demo-feed generator
    src/ff_inbox.c           # S24a — Signals inbox -> thread view-model
    src/ff_power_fsm.c       # S26 slice b — PWR-button press-timing FSM + reboot BOOT-release guard
    src/ff_idle.c            # S26 slice c — inactivity -> dim -> screen off
    src/ff_notify.c          # S26 slice d — notification queue (message banner)
    src/ff_button.c          # S26 slice e — generic debounced push-button (BOOT-as-home)
    src/ff_rally.c           # tech-debt sprint — rally place/name/when logic (moved from ff_shell.c)
    src/ff_sound.c           # S27 — sound event vocabulary, tone patterns, quiet-hours policy, priority
)
