#!/usr/bin/env bash
#
# gen_swift_protos.sh — regenerate the SwiftProtobuf sources under
# app/FireflyKit/Sources/MeshtasticProto/ from meshtastic/protobufs.
#
# This is the Swift twin of firmware/meshclient/tools/gen_nanopb.sh, and it
# deliberately shares that script's TWO pins:
#
#   MESHTASTIC_PROTOBUFS_COMMIT — the same protobuf revision, so the phone
#       app and the puck's meshclient speak a bit-identical wire version.
#       If you bump one script's pin you MUST bump the other's in the same
#       PR; app/FireflyKit/Tests/MeshtasticProtoTests asserts the two
#       scripts still name the same commit, and fails naming both values.
#   PROTO_FILES — the same mesh.proto transitive closure plus admin.proto,
#       for the same reasons gen_nanopb.sh documents inline.
#
# The output IS committed (Sources/MeshtasticProto/*.pb.swift) so a normal
# `swift build` / `xcodebuild` never needs protoc, a plugin, or the
# network — only this script does, and only when a maintainer deliberately
# moves the pin.
#
# Requirements to RUN this script (not to build the app):
#   - protoc                (brew install protobuf)
#   - protoc-gen-swift      (brew install swift-protobuf)
#   - network access to clone meshtastic/protobufs
#
# Usage:  app/tools/gen_swift_protos.sh [output_dir]
set -euo pipefail

# ---------------------------------------------------------------------------
# Pin — MUST equal MESHTASTIC_PROTOBUFS_COMMIT in
# firmware/meshclient/tools/gen_nanopb.sh. See above.
# ---------------------------------------------------------------------------
MESHTASTIC_PROTOBUFS_COMMIT="1b4cb00f3d6b0d620354a11fdd1e0b592f3cb7f5"
MESHTASTIC_PROTOBUFS_REPO="https://github.com/meshtastic/protobufs.git"

PROTO_FILES=(
    meshtastic/mesh.proto
    meshtastic/channel.proto
    meshtastic/config.proto
    meshtastic/device_ui.proto
    meshtastic/module_config.proto
    meshtastic/atak.proto
    meshtastic/portnums.proto
    meshtastic/telemetry.proto
    meshtastic/xmodem.proto
    meshtastic/admin.proto
    meshtastic/connection_status.proto
)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT_DIR="${1:-${REPO_ROOT}/app/FireflyKit/Sources/MeshtasticProto}"
NANOPB_SCRIPT="${REPO_ROOT}/firmware/meshclient/tools/gen_nanopb.sh"

command -v protoc >/dev/null 2>&1 || { echo "error: protoc not found (brew install protobuf)" >&2; exit 1; }
command -v protoc-gen-swift >/dev/null 2>&1 || {
    echo "error: protoc-gen-swift not found (brew install swift-protobuf)" >&2; exit 1; }

# Fail loudly rather than silently generating a Swift client that speaks a
# different protobuf revision than the puck's C client.
nanopb_pin="$(sed -n 's/^MESHTASTIC_PROTOBUFS_COMMIT="\(.*\)".*/\1/p' "${NANOPB_SCRIPT}")"
if [ "${nanopb_pin}" != "${MESHTASTIC_PROTOBUFS_COMMIT}" ]; then
    echo "error: protobuf pin drift." >&2
    echo "  gen_nanopb.sh     : ${nanopb_pin}" >&2
    echo "  gen_swift_protos  : ${MESHTASTIC_PROTOBUFS_COMMIT}" >&2
    echo "  Bump both, in the same PR." >&2
    exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "==> cloning meshtastic/protobufs @ ${MESHTASTIC_PROTOBUFS_COMMIT}"
git clone --quiet "${MESHTASTIC_PROTOBUFS_REPO}" "${WORK_DIR}/protobufs"
git -C "${WORK_DIR}/protobufs" checkout --quiet "${MESHTASTIC_PROTOBUFS_COMMIT}"

echo "==> generating into ${OUT_DIR}"
mkdir -p "${OUT_DIR}"
find "${OUT_DIR}" -name '*.pb.swift' -delete

(
    cd "${WORK_DIR}/protobufs"
    protoc \
        -I . \
        --swift_out="${OUT_DIR}" \
        --swift_opt=Visibility=Public \
        --swift_opt=FileNaming=DropPath \
        "${PROTO_FILES[@]}"
)

# Record what produced these files, next to them.
cat > "${OUT_DIR}/GENERATED.md" <<MARKER
# Generated — do not edit by hand

\`*.pb.swift\` in this directory is generated by
\`app/tools/gen_swift_protos.sh\` from
[meshtastic/protobufs](https://github.com/meshtastic/protobufs) at commit
\`${MESHTASTIC_PROTOBUFS_COMMIT}\` — the SAME commit
\`firmware/meshclient/tools/gen_nanopb.sh\` pins for the puck's nanopb C
sources, so both clients speak an identical wire version.

Generator: \`$(protoc --version)\` + \`$(protoc-gen-swift --version)\`.

To move the pin, edit BOTH scripts and re-run BOTH.
MARKER

echo "==> done. Generated files:"
find "${OUT_DIR}" -name '*.pb.swift' | sort
